users/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, EmailField, BooleanField
from wtforms.validators import DataRequired, Email, ValidationError, Length, EqualTo
import re
from flask_wtf import RecaptchaField


# handles register form inputs
class RegisterForm(FlaskForm):

    # Validation functions
    def character_check(self, field):
        exclude_chars = "*?!'^+%&/()=}][{$#@<>"

        for char in field.data:
            if char in exclude_chars:
                raise ValidationError(f"Character {char} is not allowed.")

    def is_valid_phone_number(self, phone):
        pattern = re.compile(r'^\d{4}-\d{3}-\d{4}$') # XXXX-XXX-XXXX pattern
        if not pattern.match(phone.data):
            raise ValidationError(f"Phone number must be in form XXXX-XXX-XXXX")

    def is_valid_password(self, password):
        pattern = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*\W)')
        if not pattern.match(password.data):
            raise ValidationError(
                f"Password must contain at least 1 uppercase letter, 1 lowercase letter, 1 digit and 1 "
                f"special character.")

    def date_of_birth_validator(self, date_of_birth):
        pattern = re.compile(r'^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/(19|20)\d{2}$')
        if not pattern.match(date_of_birth.data):
            raise ValidationError(f"Invalid date, must be a valid DD/MM/YYYY")

    def postcode_validator(self, postcode):
        pattern = re.compile(r'^([A-Z][0-9]\s[0-9][A-Z]{2}|[A-Z][0-9]{2}\s[0-9][A-Z]{2}|[A-Z]{2}[0-9]\s[0-9][A-Z]{2})$')
        if not pattern.match(postcode.data):
            raise ValidationError(f"Invalid postcode, must be XY YXX, XYY YXX or XXY YXX where X is an uppercase "
                                  f"letter and Y is a digit.")

    # assigning validators
    email = EmailField(validators=[Email(), DataRequired()])
    firstname = StringField(validators=[character_check, DataRequired()])
    lastname = StringField(validators=[character_check, DataRequired()])
    phone = StringField(validators=[is_valid_phone_number, DataRequired()])
    password = PasswordField(validators=[Length(min=6, max=12), is_valid_password, DataRequired()])
    confirm_password = PasswordField(validators=[DataRequired(), EqualTo('password', message='Both password fields '
                                                                                             'must be equal!')])
    date_of_birth = StringField(validators=[DataRequired(), date_of_birth_validator])
    postcode = StringField(validators=[DataRequired(), postcode_validator])
    submit = SubmitField()


# Handles login form data
class LoginForm(FlaskForm):
    username = EmailField('Username', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    postcode = StringField('Postcode', validators=[DataRequired()])
    pin = StringField(validators=[DataRequired()])
    recaptcha = RecaptchaField()
    submit = SubmitField()


# Form for resetting password
class PasswordForm(FlaskForm):

    def is_valid_password(self, new_password):
        pattern = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*\W)')
        if not pattern.match(new_password.data):
            raise ValidationError(
                f"Password must contain at least 1 uppercase letter, 1 lowercase letter, 1 digit and 1 "
                f"special character.")

    current_password = PasswordField(id='password', validators=[DataRequired()])
    show_password = BooleanField('Show password', id='check')
    new_password = PasswordField(
        validators=[DataRequired(), Length(min=6, max=12, message="Must be between 6 and 12 characters in length"),
                    is_valid_password])
    confirm_new_password = PasswordField(
        validators=[DataRequired(), EqualTo('new_password', message='Both new password fields must be equal')])
    submit = SubmitField('Change Password')

users/views.py
# IMPORTS
import logging
from datetime import datetime

import bcrypt
from flask import Blueprint, render_template, flash, redirect, url_for, session, request
from markupsafe import Markup
from flask_login import login_required, current_user

from app import db, requires_roles
from models import User
from users.forms import RegisterForm, LoginForm, PasswordForm
from flask_login import login_user, logout_user

# CONFIG
users_blueprint = Blueprint('users', __name__, template_folder='templates')


# VIEWS
# view registration
@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    # create signup form object
    form = RegisterForm()

    # if request method is POST or form is valid
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # if this returns a user, then the email already exists in database
        # if email already exists redirect user back to signup page with error message so user can try again
        if user:
            flash('Email address already exists')
            return render_template('users/register.html', form=form)

        # create a new user with the form data
        new_user = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        phone=form.phone.data,
                        password=form.password.data,
                        date_of_birth=form.date_of_birth.data,
                        postcode=form.postcode.data,
                        role='user')

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()

        # stores users username in apps session for setup_2fa to access
        session['username'] = new_user.email

        # logs user registration
        logging.warning('SECURITY - User registration [%s, %s]', form.email.data, request.remote_addr)

        # sends user to login page
        return redirect(url_for('users.setup_2fa'))
    # if request method is GET or form not valid re-render signup page
    return render_template('users/register.html', form=form)


# view user login
@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    # if user hasn't logged in before set to 0
    if not session.get('authentication_attempts'):
        session['authentication_attempts'] = 0

    loginForm = LoginForm()
    # checks if the form data is valid
    if loginForm.validate_on_submit():

        user = User.query.filter_by(email=loginForm.username.data).first()
        # checks login details are correct
        if not user or not user.verify_password(loginForm.password.data) or not user.verify_pin(
                loginForm.pin.data) or not user.verify_postcode(loginForm.postcode.data):
            session['authentication_attempts'] += 1
            logging.warning('SECURITY - Invalid Log In Attempt [%s, %s]', loginForm.username.data, request.remote_addr)

            # max login attempts exceeded
            if session.get('authentication_attempts') >= 3:
                flash(Markup('Number of incorrect login attempts exceeded. Please click <a href="/reset"> here </a> '
                             'to reset.'))
                return render_template('users/login.html')

            flash('Please check your login details and try again, {} login attempts remaining'.format(
                3 - session.get('authentication_attempts')))
            return render_template('users/login.html', loginForm=loginForm)
        else:
            # logs user in
            login_user(user)
            # logs the login
            logging.warning('SECURITY - User login [%s, %s, %s]', current_user.id, loginForm.username.data,
                            request.remote_addr)
            # update user details in database
            current_user.last_login = current_user.current_login
            current_user.current_login = datetime.now()
            current_user.last_ip = current_user.current_ip
            current_user.current_ip = request.remote_addr
            current_user.successful_logins = current_user.successful_logins + 1
            db.session.commit()

            if user.role == 'admin':
                return redirect(url_for('admin.admin'))
            else:
                return redirect(url_for('index'))

    return render_template('users/login.html', loginForm=loginForm)


# view user account
@users_blueprint.route('/account')
@login_required
@requires_roles('admin', 'user')
def account():
    return render_template('users/account.html',
                           acc_no=current_user.id,
                           email=current_user.email,
                           firstname=current_user.firstname,
                           lastname=current_user.lastname,
                           phone=current_user.phone,
                           date_of_birth=current_user.date_of_birth,
                           postcode=current_user.postcode)


@users_blueprint.route('/logout')
@login_required
def logout():
    # log user logout
    logging.warning('SECURITY - User log out [%s, %s, %s]', current_user.id, current_user.email,
                    request.remote_addr)
    logout_user()
    return redirect(url_for('index'))


@users_blueprint.route('/setup_2fa')
def setup_2fa():
    if 'username' not in session:
        return redirect(url_for('index'))
    # find user
    user = User.query.filter_by(email=session['username']).first()

    if not user:
        return redirect(url_for('index'))

    del session['username']
    return render_template('users/setup_2fa.html', email=user.email, uri=user.get_2fa_uri()), 200, {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'
    }


# reset login if locked out
@users_blueprint.route('/reset')
def reset():
    session['authentication_attempts'] = 0
    return redirect(url_for('users.login'))


@users_blueprint.route('/update_password', methods=['GET', 'POST'])
def update_password():
    form = PasswordForm()

    if form.validate_on_submit():
        # checks current password
        if not current_user.verify_password(form.current_password.data):
            flash("Incorrect current password")
            return render_template('users/update_password.html', form=form)
        else:
            # checks new password isn't same as old password
            if current_user.verify_password(form.new_password.data):
                flash('New password must be different to current password')
                return render_template('users/update_password.html', form=form)
            else:
                # sets and hashes new password
                current_user.password = bcrypt.hashpw(form.new_password.data.encode('utf-8'), bcrypt.gensalt())
                db.session.commit()
                flash('Password changed successfully')

        return redirect(url_for('users.account'))

    return render_template('users/update_password.html', form=form)

templates/users/account.html
{% extends "base.html" %}

{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
    {% endwith %}

    <div class="column is-6 is-offset-3">
        <h3 class="title">Your Account</h3>

        <div class="box">
            <table class="table">
            <tbody>
                <tr>
                    <th>Account No.</th>
                    <th>{{ acc_no }}</th>
                </tr>
                <tr>
                    <th>Email</th>
                    <th>{{ email }}</th>
                </tr>
                <tr>
                    <th>First Name</th>
                    <th>{{ firstname }}</th>
                </tr>
                <tr>
                    <th>Last Name</th>
                    <th>{{ lastname }}</th>
                </tr>
                <tr>
                    <th>Phone No.</th>
                    <th>{{ phone }}</th>
                </tr>
                <tr>
                    <th>Date of Birth</th>
                    <th>{{ date_of_birth }}</th>
                </tr>
                <tr>
                    <th>Postcode</th>
                    <th>{{ postcode }}</th>
                </tr>
                <tr>
                    <th>Password</th>
                    <td><a style='color: blue' href="{{ url_for('users.update_password') }}">Change Password</a></td>
                </tr>
            </tbody>
            </table>
        </div>
    </div>


{% endblock %}

templates/users/login.html
{% extends "base.html" %}

{% block content %}
    <div class="column is-5 is-offset-4">
        <h3 class="title">Login</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
            {% if loginForm %}
                <form method="POST">
                    <div class="field">
                        {{ loginForm.csrf_token() }}
                        <div class="control">
                            {{ loginForm.username(class="input", placeholder="Username") }}
                            {% for error in loginForm.username.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ loginForm.password(class="input", placeholder="Password") }}
                            {% for error in loginForm.password.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ loginForm.postcode(class="input", placeholder="Postcode") }}
                            {% for error in loginForm.postcode.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ loginForm.recaptcha }}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ loginForm.pin(class="input", placeholder="Time-based PIN") }}
                        </div>
                    </div>
                    <div>
                        {{ loginForm.submit(class="button is-info is-centered") }}
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/register.html
{% extends "base.html" %}

{% block content %}
    <div class="column is-5 is-offset-4">
        <h3 class="title is-3">Register</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}. Go to <a href="{{ url_for('users.login') }}">login page</a>.
                    </div>
                {% endif %}
            {% endwith %}
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.email(class="input", placeholder="Email") }}
                        {% for error in form.email.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.firstname(class="input", placeholder="First Name") }}
                        {% for error in form.firstname.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.lastname(class="input", placeholder="Last Name") }}
                        {% for error in form.lastname.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.phone(class="input", placeholder="Phone") }}
                        {% for error in form.phone.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.password(class="input", placeholder="Password") }}
                        {% for error in form.password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                        {% for error in form.confirm_password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>

                </div>
                <div class="field">
                    <div class="control">
                        {{ form.date_of_birth(class="input", placeholder="Date of Birth") }}
                        {% for error in form.date_of_birth.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>

                </div>
                <div class="field">
                    <div class="control">
                        {{ form.postcode(class="input", placeholder="Postcode") }}
                        {% for error in form.postcode.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/setup_2fa.html
{% extends "base.html" %}

{% block content %}
    <div class="column is-5 is-offset-4">
        <h3 class="title">Setup 2-Factor Authentication</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}

            <p>To set up 2-factor authentication under the account name {{ username }},
            scan the following QR code with your smartphone's authenticator app:</p>

            <p><img src="{{ qrcode(uri, box_size=5, border=5) }}"></p>

            <p>Once set up, please go to the <a href="{{ url_for('users.login') }}"><u>Login</u></a> page</p>

        </div>
    </div>
{% endblock %}

templates/users/update_password.html
{% extends 'base.html' %}

{% block content %}
    <script type="text/javascript" src="{{ url_for('static', filename='listeners.js') }}"></script>
    <div class="column is-5 is-offset-4">
        <h3 class="title">Change Password</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.current_password(class="input", placeholder="Current Password") }}
                        {% for error in form.current_password.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.show_password() }}
                        {{ form.show_password.label }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.new_password(class="input", placeholder="New Password") }}
                        {% for error in form.new_password.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_new_password(class="input", placeholder="Confirm New Password") }}
                        {% for error in form.confirm_new_password.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}